Bug1999146-TPS-install-Python-error-text
This patch is an attempt to fix the TPS installation issue regarding:
   TypeError: __init__() got an unexpected keyword argument 'text'

My research shows that it's likely having to do with Python version
differences.  In Python 3.6.8, "text" is possibly not yet introduced
so I"m trying out "universal_newlines".

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1999146