Fix compile issue in RA_Token.cpp
GCC 6 is more strict than GCC 5 and earlier. It refuses to initialize a
char[] with 'int' initializers because char is signed while the its are
values from 0 to 255.

RA_Token.cpp:989:7: error: narrowing conversion of ‘194’ from ‘int’ to
‘char’ inside { }

https://fedorahosted.org/pki/attachment/ticket/2221