Py3 compatibility: set default for verbosity to 0
The default value for argparser's verbosity was None, but None can't be
compared to 2 in Python 3.

TypeError: unorderable types: NoneType() >= int()