Disable GPG check in CI
The GPG check has been disabled due to the following issue
during build dependency installation on F32:

Package libuv-1.40.0-1.fc32.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED