EST: fix build with jackson-2.10
Some platforms we target have jackson-2.10.  Build is failing due to
use of a JsonGenerator method that was only added in v2.11:

    error: no suitable method found for writeArray(String[],int,int)
        generator.writeArray(roles, 0, roles.length);

Update our implementation to avoid use of this method.

Part of: https://github.com/dogtagpki/pki/issues/3297